name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_GRAPH_REF }}
    steps:
      - uses: actions/checkout@v3

      - name: test
        run: |
          echo $APOLLO_KEY

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.10.0 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Run check against prod
        run: |
          rover graph publish $APOLLO_KEY --schema src/generated/schema.graphql
