name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.10.0 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Run check against prod
        run: |
          rover graph publish ${{ secrets.APOLLO_GRAPH_REF }} --schema src/generated/schema.graphql
